### ISSUE TITLE
New Cuda

### ISSUE THREAD

**Issue by LemonRiz** [Atinoda/text-generation-webui-docker#28]
I think the newest Cuda has broken the docker deployment for vast.ai.

![image](https://github.com/Atinoda/text-generation-webui-docker/assets/114920968/b6381565-cea7-4b69-a849-80f183418351)

**Comment by Atinoda** [comment]
What variant and version produces this error? I can run the latest stable `default` image with ExLlamav2 without any issues on my dev server.

**Comment by LemonRiz** [comment]
I just follow this guide: https://vast.ai/docs/guides/oobabooga
I add --api and --public api tags to the start up

`env | grep _ >> /etc/environment; pip install accelerate -U; pip install protobuf; cd /src; /scripts/docker-entrypoint.sh python3 /app/server.py --listen --api --public-api --share;`

Whenever I try to load a model I get the error I posted as an image when I opened the issue.

**Comment by Atinoda** [comment]
The issue seems to be with Vast.ai's implementation - for instance, I'm not
sure why they are running `pip install` commands before launching the image
(nor am I sure where they are running those commands). I recommend that you
flag this error to their tech support and ask them to check/update the run
templates.

**Comment by LemonRiz** [comment]
Thank you. Very prompt

**Comment by Atinoda** [comment]
Thanks for the extra info and links - I always like to hear about how
people are using the image!
