### ISSUE TITLE
Can't launch the UI by docker compose up

### ISSUE THREAD

**Issue by silverwind63** [Atinoda/text-generation-webui-docker#47]
```
WARN[0000] /mnt/extradisk/text-generation-webui-docker/docker-compose.yml: `version` is obsolete 
Attaching to text-generation-webui
Error response from daemon: failed to create endpoint text-generation-webui on network text-generation-webui-docker_default: failed to add the host (veth7a52283) <=> sandbox (vetheb0e327) pair interfaces: operation not supported
```
I have git pull and docker compose pull but the issue is still unsolved. Thanks for your help!

**Comment by Atinoda** [comment]
Hi @silverwind63, it seems there is a problem with the system that you are using to run the container. You must provide more detail than this for troubleshooting! I suggest to have a conversation with ChatGPT, Gemini, or Claude - they all have free tiers, and can talk you through the set up and how to report an issue on Github. I am going to close the issue for now because it is not related to this project specifically - but please fell welcome to re-open if you are still having problems after getting Docker running.
